# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 021fb53a0daad3472e17321f81b07cd35c226daca730e25dd7ded9dab04473c057c5797978a1222839d5dca0ef7b8c6142625e1a97d176aede13d7a9b6b07488

test:
  secret_key_base: 3111388e19c57a26245765834c93bb458ffbb68d0434f79c5a29730ad8eab5d540cb1761f89dbc6fab30554e698e3046bfba77f56c6680f11ab155610d09ad36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
